route:
  receiver: 'slack'
  group_by: ['blackbox']
  group_interval: 2m
  repeat_interval: 5m

receivers:
  - name: 'slack'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/T0'
        channel: '01nblackbox'
        username: 'Prometheus'
        text: |- 
                "{{ .CommonAnnotations.summary }} 
                Details:
                {{ .CommonLabels.severity }} 
                Severity: 
                {{ .CommonLabels.severity }} 
                URL: {{ .CommonAnnotations.url }} . "
