global:
  scrape_interval: 15s
  evaluation_interval: 15s


rule_files:
  - '/etc/prometheus/alert.rules'

alerting: 
 alertmanagers: 
 - static_configs: 
   - targets: 
     - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
              - "https://a.ir"
              - "https://io..ir"
              - "http://mllllllllllll.net"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
